### ISSUE TITLE
Exception when using networks without externalities

### ISSUE THREAD

**Issue by justinian336** [sansan-inc/lighthergm#2]
If you use `simulate_hergm` to simulate networks without externalities, an exception gets raised.
For example, the following formula:
```
g ~ edges + nodematch('x')
```
This raises the following exception:
```
parse(text = x, keep.source = FALSE) でエラー: 
  <text>:2:0:  想定外の入力の終端です 
1: seed_network_within ~ 
   ^
```
I guess it's an issue with the way the formula gets divided into the between and within parts.
As a workaround, you can use a formula that includes some externality term and then set its coefficient to zero.

if you use `lighthergm::hergm` to estimate a model without externalities, the following error is raised:
```
Estimate between-block parameters
 parse(text = x, keep.source = FALSE) でエラー: 
  <text>:2:0:  想定外の入力の終端です 
1: g_logit ~  
```

**Comment by meleangelo** [comment]
That sounds like a simple workaround. I don't think this happens with estimation.

**Comment by justinian336** [comment]
@meleangelo I get an exception on the `lighthergm::hergm` method when running it like this. I added the 2-star term for simulation to avoid the error on `simulate_hergm`, but I didn't include it in the estimation part. This should raise an error when computing the within coefficients. Can you check if it doesn't happen for you? I'm using the latest version on the `main` branch.

```
sim_ergm_control <- ergm::control.simulate.formula(
  MCMC.burnin = 1000000,
  MCMC.interval = 100000
)

K <- 10
N <- 200
formula_1 <- g ~ edges + nodematch("x") + kstar(2)
x <- sample(c(1, 2), size=N, replace = TRUE)
block <- sample(1:K, size=N, replace = TRUE)

nodes_data <- tibble(x=x, node_id=as.character(1:N), block=block)

coef_between <- c(-6.5, 0)
coef_within <- c(-4.5, 5, 0.)

sim_net_1 <- lighthergm::simulate_hergm(
  formula_for_simulation = formula_1,
  data_for_simulation = nodes_data,
  colname_vertex_id = 'node_id',
  colname_block_membership = 'block',
  coef_between_block = coef_between,
  coef_within_block = coef_within,
  ergm_control = sim_ergm_control,
  n_sim = 1
)

ggnet2(sim_net_1, node.color = nodes_data$x, node.size = 1, edge.alpha = 0.1)

res_sim_1 <- lighthergm::hergm(
  object = sim_net_1 ~ edges + nodematch("x"),
  n_clusters = 5,
  n_em_step_max = 5,
  initialization_method = 1,
  clustering_with_features = FALSE,
  verbose=2
)
```

**Comment by komatsuna4747** [comment]
I replicated the error.

https://github.com/sansan-inc/lighthergm/blob/81f3df54518aca3df9490ffc02a59053fb407776/lighthergm/R/estimate_between_param.R#L45-L55

When there are no externality terms in the formula, `dep_terms` is `integer(0)`. And subsetting `varnames` by `varnamees[-dep_terms]` yields `character(0)`, which causes the error in the last line of the code above.

```
Browse[2]> varnames
[1] "edges"            "nodematch(\"x\")"
Browse[2]> dep_terms
integer(0)
Browse[2]> varnames[-dep_terms]
character(0)
```

One solution would be to remove `which()` when making `dep_terms`:
```
Browse[2]> new_dep_terms <- terms %>% purrr::map(function(t) {
+     dep <- t$dependence
+     is_dep <- is.null(dep) || dep
+ }) %>% unlist()
Browse[2]> new_dep_terms
[1] FALSE FALSE
Browse[2]> varnames[!new_dep_terms]
[1] "edges"            "nodematch(\"x\")"
```
This should also work when there are externality terms in the formula.
